# Generated by Django 4.1 on 2023-04-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('bgg_url', models.URLField()),
                ('game_id', models.IntegerField()),
                ('names', models.CharField(max_length=255)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('avg_time', models.IntegerField()),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('year', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('geek_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('image_url', models.URLField()),
                ('age', models.IntegerField()),
                ('mechanic', models.CharField(max_length=255)),
                ('owned', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('designer', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Category_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.categories')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
